name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"   # match your local env

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Dev + runtime deps for tests and lint
          pip install -r requirements.txt || true
          pip install -r requirements-dev.txt || true
          # Fallback if you don’t keep req files:
          pip install pytest flake8 fastapi uvicorn scikit-learn pandas numpy pydantic joblib

      - name: Lint (flake8)
        run: flake8 .

      - name: Test (pytest)
        run: pytest -q
